"""Add cascading deletes for organization and owner

Revision ID: 5799f5129656
Revises: 2bcf7db67a78
Create Date: 2026-05-10 23:30:44.226379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5799f5129656'
down_revision: Union[str, Sequence[str], None] = '2bcf7db67a78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('order_items_order_id_fkey'), 'order_items', type_='foreignkey')
    op.drop_constraint(op.f('order_items_product_id_fkey'), 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('orders_assigned_agent_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_organization_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['assigned_agent_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'orders', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('organization_config_ai_organization_id_fkey'), 'organization_config_ai', type_='foreignkey')
    op.create_foreign_key(None, 'organization_config_ai', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_org_owner_id', 'organizations', 'users', ['owner_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.drop_constraint(op.f('platform_connectors_organization_id_fkey'), 'platform_connectors', type_='foreignkey')
    op.create_foreign_key(None, 'platform_connectors', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('products_organization_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.drop_constraint(op.f('refresh_tokens_organization_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'refresh_tokens', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('team_members_user_id_fkey'), 'team_members', type_='foreignkey')
    op.drop_constraint(op.f('team_members_team_id_fkey'), 'team_members', type_='foreignkey')
    op.create_foreign_key(None, 'team_members', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'team_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('teams_organization_id_fkey'), 'teams', type_='foreignkey')
    op.create_foreign_key(None, 'teams', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('users_organization_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_organization_id_fkey'), 'users', 'organizations', ['organization_id'], ['id'])
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.create_foreign_key(op.f('teams_organization_id_fkey'), 'teams', 'organizations', ['organization_id'], ['id'])
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.create_foreign_key(op.f('team_members_team_id_fkey'), 'team_members', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(op.f('team_members_user_id_fkey'), 'team_members', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_organization_id_fkey'), 'refresh_tokens', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_organization_id_fkey'), 'products', 'organizations', ['organization_id'], ['id'])
    op.drop_constraint(None, 'platform_connectors', type_='foreignkey')
    op.create_foreign_key(op.f('platform_connectors_organization_id_fkey'), 'platform_connectors', 'organizations', ['organization_id'], ['id'])
    op.drop_constraint('fk_org_owner_id', 'organizations', type_='foreignkey')
    op.drop_constraint(None, 'organization_config_ai', type_='foreignkey')
    op.create_foreign_key(op.f('organization_config_ai_organization_id_fkey'), 'organization_config_ai', 'organizations', ['organization_id'], ['id'])
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_organization_id_fkey'), 'orders', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(op.f('orders_assigned_agent_id_fkey'), 'orders', 'users', ['assigned_agent_id'], ['id'])
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('order_items_product_id_fkey'), 'order_items', 'products', ['product_id'], ['id'])
    op.create_foreign_key(op.f('order_items_order_id_fkey'), 'order_items', 'orders', ['order_id'], ['id'])
    op.alter_column('order_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
