"""add_tax_and_delivery_charge_to_orders

Revision ID: 468194a27b80
Revises: 7e74327a6da7
Create Date: 2026-05-30 17:22:05.296317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '468194a27b80'
down_revision: Union[str, Sequence[str], None] = '7e74327a6da7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_audit_logs_org_created', 'audit_logs', ['organization_id', 'created_at'], unique=False)
    op.create_index('idx_audit_logs_organization_id', 'audit_logs', ['organization_id'], unique=False)
    op.create_index('idx_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('idx_order_items_order_id', 'order_items', ['order_id'], unique=False)
    op.create_index('idx_order_items_product_id', 'order_items', ['product_id'], unique=False)
    op.add_column('orders', sa.Column('tax_amount', sa.Integer(), server_default='0', nullable=False))
    op.add_column('orders', sa.Column('delivery_charge', sa.Integer(), server_default='0', nullable=False))
    op.create_index('idx_orders_assigned_agent_id', 'orders', ['assigned_agent_id'], unique=False)
    op.create_index('idx_orders_org_created', 'orders', ['organization_id', 'created_at'], unique=False)
    op.create_index('idx_orders_org_status', 'orders', ['organization_id', 'status'], unique=False)
    op.create_index('idx_orders_organization_id', 'orders', ['organization_id'], unique=False)
    op.create_index('idx_products_org_name', 'products', ['organization_id', 'name'], unique=False)
    op.create_index('idx_products_org_sku', 'products', ['organization_id', 'sku'], unique=False)
    op.create_index('idx_products_organization_id', 'products', ['organization_id'], unique=False)
    op.create_index('idx_team_members_team_user', 'team_members', ['team_id', 'user_id'], unique=False)
    op.create_index('idx_team_members_user_id', 'team_members', ['user_id'], unique=False)
    op.create_index('idx_teams_organization_id', 'teams', ['organization_id'], unique=False)
    op.create_index('ix_users_organization_id', 'users', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_organization_id', table_name='users')
    op.drop_index('idx_teams_organization_id', table_name='teams')
    op.drop_index('idx_team_members_user_id', table_name='team_members')
    op.drop_index('idx_team_members_team_user', table_name='team_members')
    op.drop_index('idx_products_organization_id', table_name='products')
    op.drop_index('idx_products_org_sku', table_name='products')
    op.drop_index('idx_products_org_name', table_name='products')
    op.drop_index('idx_orders_organization_id', table_name='orders')
    op.drop_index('idx_orders_org_status', table_name='orders')
    op.drop_index('idx_orders_org_created', table_name='orders')
    op.drop_index('idx_orders_assigned_agent_id', table_name='orders')
    op.drop_column('orders', 'delivery_charge')
    op.drop_column('orders', 'tax_amount')
    op.drop_index('idx_order_items_product_id', table_name='order_items')
    op.drop_index('idx_order_items_order_id', table_name='order_items')
    op.drop_index('idx_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_organization_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_org_created', table_name='audit_logs')
    # ### end Alembic commands ###
