"""refactor_platform_connectors

Revision ID: 7e74327a6da7
Revises: a7032126f5ce
Create Date: 2026-05-21 23:53:41.897781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e74327a6da7'
down_revision: Union[str, Sequence[str], None] = 'a7032126f5ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('platform_connectors_organization_id_fkey'), 'platform_connectors', type_='foreignkey')
    op.drop_constraint(op.f('platform_connectors_platform_id_fkey'), 'platform_connectors', type_='foreignkey')
    op.drop_index(op.f('ix_platforms_name'), table_name='platforms')
    op.drop_table('platforms')
    op.add_column('platform_connectors', sa.Column('business_id', sa.Uuid(), nullable=False))
    op.add_column('platform_connectors', sa.Column('platform', sa.String(length=50), nullable=False))
    op.add_column('platform_connectors', sa.Column('platform_account_id', sa.String(length=255), nullable=False))
    op.add_column('platform_connectors', sa.Column('platform_account_name', sa.String(length=255), nullable=True))
    op.add_column('platform_connectors', sa.Column('tokens', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('platform_connectors', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True))
    op.add_column('platform_connectors', sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False))
    op.alter_column('platform_connectors', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('platform_connectors', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_org_platform_connector'), 'platform_connectors', type_='unique')
    op.create_index('idx_platform_connectors_business_id', 'platform_connectors', ['business_id'], unique=False)
    op.create_index('idx_platform_connectors_routing', 'platform_connectors', ['platform', 'platform_account_id'], unique=False)
    op.create_unique_constraint('unique_business_platform_account', 'platform_connectors', ['business_id', 'platform', 'platform_account_id'])
    op.create_unique_constraint('uq_business_platform', 'platform_connectors', ['business_id', 'platform'])
    op.create_foreign_key(None, 'platform_connectors', 'organizations', ['business_id'], ['id'], ondelete='CASCADE')
    op.drop_column('platform_connectors', 'refresh_token')
    op.drop_column('platform_connectors', 'platform_id')
    op.drop_column('platform_connectors', 'token_expires_at')
    op.drop_column('platform_connectors', 'is_active')
    op.drop_column('platform_connectors', 'organization_id')
    op.drop_column('platform_connectors', 'external_page_id')
    op.drop_column('platform_connectors', 'access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_connectors', sa.Column('access_token', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.add_column('platform_connectors', sa.Column('external_page_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('platform_connectors', sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('platform_connectors', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('platform_connectors', sa.Column('token_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('platform_connectors', sa.Column('platform_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('platform_connectors', sa.Column('refresh_token', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'platform_connectors', type_='foreignkey')
    op.create_foreign_key(op.f('platform_connectors_platform_id_fkey'), 'platform_connectors', 'platforms', ['platform_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('platform_connectors_organization_id_fkey'), 'platform_connectors', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_business_platform', 'platform_connectors', type_='unique')
    op.drop_constraint('unique_business_platform_account', 'platform_connectors', type_='unique')
    op.drop_index('idx_platform_connectors_routing', table_name='platform_connectors')
    op.drop_index('idx_platform_connectors_business_id', table_name='platform_connectors')
    op.create_unique_constraint(op.f('uq_org_platform_connector'), 'platform_connectors', ['organization_id', 'platform_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('platform_connectors', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('platform_connectors', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('platform_connectors', 'status')
    op.drop_column('platform_connectors', 'metadata')
    op.drop_column('platform_connectors', 'tokens')
    op.drop_column('platform_connectors', 'platform_account_name')
    op.drop_column('platform_connectors', 'platform_account_id')
    op.drop_column('platform_connectors', 'platform')
    op.drop_column('platform_connectors', 'business_id')
    op.create_table('platforms',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('platforms_pkey'))
    )
    op.create_index(op.f('ix_platforms_name'), 'platforms', ['name'], unique=True)
    # ### end Alembic commands ###
