"""create customers table and links

Revision ID: fde212f1d0ed
Revises: 0ea275879023
Create Date: 2026-06-05 10:41:07.279965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fde212f1d0ed'
down_revision: Union[str, Sequence[str], None] = '0ea275879023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('platform', postgresql.ENUM('INSTAGRAM', 'TIKTOK', 'FACEBOOK_MESSENGER', 'CHATBOX', 'TELEGRAM', name='platformtype', create_type=False), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('social_media_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_customers_org_platform_external', 'customers', ['organization_id', 'platform', 'external_id'], unique=True)
    op.create_index('idx_customers_organization_id', 'customers', ['organization_id'], unique=False)
    op.add_column('orders', sa.Column('customer_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('orders_customer_id_fkey', 'orders', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    op.add_column('tickets', sa.Column('customer_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('tickets_customer_id_fkey', 'tickets', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tickets_customer_id_fkey', 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'customer_id')
    op.drop_constraint('orders_customer_id_fkey', 'orders', type_='foreignkey')
    op.drop_column('orders', 'customer_id')
    op.drop_index('idx_customers_organization_id', table_name='customers')
    op.drop_index('idx_customers_org_platform_external', table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
