# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from shared.proto import service_pb2 as shared_dot_proto_dot_service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in shared/proto/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/microservices.AuthService/Register',
                request_serializer=shared_dot_proto_dot_service__pb2.RegisterRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_service__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.VerifyEmail = channel.unary_unary(
                '/microservices.AuthService/VerifyEmail',
                request_serializer=shared_dot_proto_dot_service__pb2.VerifyEmailRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_service__pb2.VerifyEmailResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/microservices.AuthService/Login',
                request_serializer=shared_dot_proto_dot_service__pb2.LoginRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_service__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.VerifyAccessToken = channel.unary_unary(
                '/microservices.AuthService/VerifyAccessToken',
                request_serializer=shared_dot_proto_dot_service__pb2.VerifyAccessTokenRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_service__pb2.VerifyAccessTokenResponse.FromString,
                _registered_method=True)
        self.RefreshToken = channel.unary_unary(
                '/microservices.AuthService/RefreshToken',
                request_serializer=shared_dot_proto_dot_service__pb2.RefreshTokenRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_service__pb2.RefreshTokenResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/microservices.AuthService/Logout',
                request_serializer=shared_dot_proto_dot_service__pb2.LogoutRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_service__pb2.LogoutResponse.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyAccessToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=shared_dot_proto_dot_service__pb2.RegisterRequest.FromString,
                    response_serializer=shared_dot_proto_dot_service__pb2.RegisterResponse.SerializeToString,
            ),
            'VerifyEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyEmail,
                    request_deserializer=shared_dot_proto_dot_service__pb2.VerifyEmailRequest.FromString,
                    response_serializer=shared_dot_proto_dot_service__pb2.VerifyEmailResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=shared_dot_proto_dot_service__pb2.LoginRequest.FromString,
                    response_serializer=shared_dot_proto_dot_service__pb2.LoginResponse.SerializeToString,
            ),
            'VerifyAccessToken': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyAccessToken,
                    request_deserializer=shared_dot_proto_dot_service__pb2.VerifyAccessTokenRequest.FromString,
                    response_serializer=shared_dot_proto_dot_service__pb2.VerifyAccessTokenResponse.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=shared_dot_proto_dot_service__pb2.RefreshTokenRequest.FromString,
                    response_serializer=shared_dot_proto_dot_service__pb2.RefreshTokenResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=shared_dot_proto_dot_service__pb2.LogoutRequest.FromString,
                    response_serializer=shared_dot_proto_dot_service__pb2.LogoutResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'microservices.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('microservices.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/microservices.AuthService/Register',
            shared_dot_proto_dot_service__pb2.RegisterRequest.SerializeToString,
            shared_dot_proto_dot_service__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/microservices.AuthService/VerifyEmail',
            shared_dot_proto_dot_service__pb2.VerifyEmailRequest.SerializeToString,
            shared_dot_proto_dot_service__pb2.VerifyEmailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/microservices.AuthService/Login',
            shared_dot_proto_dot_service__pb2.LoginRequest.SerializeToString,
            shared_dot_proto_dot_service__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyAccessToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/microservices.AuthService/VerifyAccessToken',
            shared_dot_proto_dot_service__pb2.VerifyAccessTokenRequest.SerializeToString,
            shared_dot_proto_dot_service__pb2.VerifyAccessTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/microservices.AuthService/RefreshToken',
            shared_dot_proto_dot_service__pb2.RefreshTokenRequest.SerializeToString,
            shared_dot_proto_dot_service__pb2.RefreshTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/microservices.AuthService/Logout',
            shared_dot_proto_dot_service__pb2.LogoutRequest.SerializeToString,
            shared_dot_proto_dot_service__pb2.LogoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
